### ISSUE TITLE
ReferenceError: __linariaStyle is not defined

### ISSUE THREAD

**Issue by JellyBrick** [aiji42/remix-esbuild-override#29]
```javascript
./libre-billboardoo-frontend/build/index.js:522
var RankHeaderStyle = __linariaStyle, headerStyle = import_core.css`
                      ^
ReferenceError: __linariaStyle is not defined
    at Object.<anonymous> (./libre-billboardoo-frontend/build/index.js:522:23)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (./libre-billboardoo-frontend/node_modules/@remix-run/serve/dist/cli.js:48:13)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
```

`remix-esbuild-override` not working with `linaria 4.x`
(working with `linaria 3.0.0-beta.x`)

**Comment by aiji42** [comment]
Sorry, linaria is no longer supported by this repository.

**Comment by andrmaz** [comment]
@JellyBrick  Is there any chance you can still share the code working with `linaria@3.0.0-beta` ?

**Comment by JellyBrick** [comment]
> @JellyBrick Is there any chance you can still share the code working with `linaria@3.0.0-beta` ?

https://github.com/wakboardoo/libre-billboardoo-frontend
