### ISSUE TITLE
Loading Macros with Emotion

### ISSUE THREAD

**Issue by scefali** [aiji42/remix-esbuild-override#30]
I am trying to figure out how to load macros so I don't get this error using `emotion`:

```
Error: Component selectors can only be used in conjunction with @emotion/babel-plugin.
    at handleInterpolation (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@emotion/serialize/dist/emotion-serialize.cjs.dev.js:92:13)
    at Object.serializeStyles (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@emotion/serialize/dist/emotion-serialize.cjs.dev.js:272:15)
    at /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@emotion/styled/base/dist/emotion-styled-base.cjs.dev.js:124:34
    at /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@emotion/react/dist/emotion-element-c24e4fdd.cjs.dev.js:66:16
    at processChild (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at handleRequest (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/app/entry.server.tsx:22:16)
```
This happens when you try to use a component selector like this:
```
const Item1 = styled("div")`
  background-color: green;
`;


const Item2 = styled("div")`
  ${Item1} {
    color: red;
  }
`;
```
None of the remix + emotion examples I've seen have component selectors and whenever I try to use it, I get the same error.

I tried two different solutions:

1. I tried using [decky](https://github.com/jarred-sumner/decky) but it looks like I need to generate the build asynchronously and I don't think that's supported.
2. I tried to use [esbuild-plugin-babel](https://www.npmjs.com/package/esbuild-plugin-babel) so I could use `@emotion/babel-plugin` but I get the following error trying to use it in my `remix.config.js` file:
```
Error: Error loading Remix config at /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/remix.config.js
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/esbuild-plugin-babel/src/index.js from /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/remix.config.js not supported.
Instead change the require of index.js in /Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/remix.config.js to a dynamic import() which is available in all CommonJS modules.
    at Object.readConfig (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@remix-run/dev/dist/config.js:84:13)
    at Object.dev (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@remix-run/dev/dist/cli/commands.js:278:18)
    at dev (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@remix-run/dev/dist/cli/run.js:184:3)
    at Object.run (/Users/scefali/Fun/remix/remix-esbuild-override/examples/remix-with-emotion/node_modules/@remix-run/dev/dist/cli/run.js:517:7)
```

I don't think I can use an ES module for `remix.config.js`. So is there any way I can do this?

**Comment by aiji42** [comment]
I'm sorry. I have no idea about this.
