### ISSUE TITLE
Issue with importing css files

### ISSUE THREAD

**Issue by repository** [aiji42/remix-esbuild-override#38]
Hello. I am having trouble using this package and the Chakra UI example provided in conjunction with importing CSS.

Log:
```
Building Remix app in production mode...
💽 Override esbuild. Your custom config can be used to build for Remix.

✘ [ERROR] [plugin css-file] Build failed with 2 errors:
error: Could not read from file: /workspaces/codespaces-blank/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js
node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js:1:23: ERROR: Could not resolve "_node-buffer-polyfill_.js"

    app/root.tsx:10:26:
      10 │ import mapboxStyles  from 'mapbox-gl/dist/mapbox-gl.css';
         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:58:12:
      58 │       build.onLoad({
         ╵             ~~~~~~

    at setup (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:58:13)
    at handlePlugins (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1277:21)
    at buildOrServeImpl (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:966:5)
    at Object.buildOrServe (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:774:5)
    at /workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:2113:17
    at new Promise (<anonymous>)
    at Object.build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:2112:14)
    at build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1959:51)
    at Object.<anonymous> (/workspaces/codespaces-blank/node_modules/remix-esbuild-override/dist/index.js:27:28)

 ✘ [ERROR] [plugin css-file] Build failed with 2 errors:
error: Could not read from file: /workspaces/codespaces-blank/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js
node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js:1:23: ERROR: Could not resolve "_node-buffer-polyfill_.js"

    app/root.tsx:11:24:
      11 │ import localStyles from "./styles.css"
         ╵                         ~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:58:12:
      58 │       build.onLoad({
         ╵             ~~~~~~

    at setup (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/compiler/plugins/cssFilePlugin.js:58:13)
    at handlePlugins (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1277:21)
    at buildOrServeImpl (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:966:5)
    at Object.buildOrServe (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:774:5)
    at /workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:2113:17
    at new Promise (<anonymous>)
    at Object.build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:2112:14)
    at build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1959:51)
    at Object.<anonymous> (/workspaces/codespaces-blank/node_modules/remix-esbuild-override/dist/index.js:27:28)


Build failed with 2 errors:
app/root.tsx:10:26: ERROR: [plugin: css-file] Build failed with 2 errors:
error: Could not read from file: /workspaces/codespaces-blank/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js
node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js:1:23: ERROR: Could not resolve "_node-buffer-polyfill_.js"
app/root.tsx:11:24: ERROR: [plugin: css-file] Build failed with 2 errors:
error: Could not read from file: /workspaces/codespaces-blank/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js
node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js:1:23: ERROR: Could not resolve "_node-buffer-polyfill_.js"
Error
    at Object.onCompileFailure (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/cli/commands.js:179:13)
    at Object.compile (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:33:134)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
    at async Object.build (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/cli/commands.js:174:3)
    at async Object.run (/workspaces/codespaces-blank/node_modules/@remix-run/dev/dist/cli/run.js:448:7)
 ```

I encountered this issue first with importing styles from react-map-gl, but it also occurs with importing any css files. I thought it was a pnpm issue, but when the packages are installed using npm the issue still occurs.

Reproduction repo: https://github.com/repository/remix-esbuild-override-css-import/blob/4cb370c7ff53808197cd3ab8494b9145aee5c9a4/app/root.tsx#L10-L11

**Comment by repository** [comment]
Apologies, I found another issue with the same issue immediately after opening this one. 😅
https://github.com/aiji42/remix-esbuild-override/issues/35#issuecomment-1385058514
